clean: ; rm *.out

run: ; g++ -Wall -Wextra -o executable.out main.cpp headers/book.h book.cpp headers/audio.h audio.cpp headers/publication.h publication.cpp headers/sales.h sales.cpp
	./executable.out